### ISSUE TITLE
With-option and xpath function

### ISSUE THREAD

**Issue by denismaier** [xatapult/markupuk-2020#2]
Hi, I'm referring to example-1a from 101-B.

This

```xml
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="3.0">

  <p:input port="source" href="input.txt"/>
  <p:output port="result"/>

  <p:wrap-sequence wrapper="text"/>
  
  <p:add-attribute match="/*" attribute-name="timestamp" attribute-value="{current-dateTime()}"/>

<p:add-attribute>
    <p:with-option name="match" select="'/*'"/>
    <p:with-option name="attribute-name" select="'another'"/>
    <p:with-option name="attribute-value" select="current-dateTime()"/>
  </p:add-attribute>

</p:declare-step>
```

gives me errors. I've figured out that we'll need to manually convert `current-dateTime()` to a string, so this would be correct:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="3.0">

  <p:input port="source" href="input.txt"/>
  <p:output port="result"/>

  <p:wrap-sequence wrapper="text"/>
  
  <p:add-attribute match="/*" attribute-name="timestamp" attribute-value="{current-dateTime()}"/>

<p:add-attribute>
    <p:with-option name="match" select="'/*'"/>
    <p:with-option name="attribute-name" select="'another'"/>
    <p:with-option name="attribute-value" select="string(current-dateTime())"/>
  </p:add-attribute>

</p:declare-step>
```

I'm currently learning xproc, so I'm wondering if there's been a change.

**Comment by xatapult** [comment]
Hi Denis,

I'm on holiday right now but will answer you as soon as I get back.

Regards,
Erik Siegel 

Op 6 mei 2024 15:27, om 15:27, Denis Maier ***@***.***> schreef:

**Comment by xatapult** [comment]
Hi Dennis,

No, there was no change. This was simply a mistake. An AVT , like in `attribute-value="{current-dateTime()}"` automatically "stringifies" its contents. When you use `<p:with-option>` you need to provide the right data type.

Regards,
Erik

**Comment by denismaier** [comment]
Thanks for the clarification, Erik. That makes sense. (The only thing where I'm unsure now is this: I think in the markup uk videos you did run the example with the now incorrect code, and it did work. But maybe the processor was just less strict back then.) Anyway, now I know how it should work, and will use it accordingly.
